'use client';

import React, { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

type Language = 'FR' | 'EN';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      return navigator.language.startsWith('fr') ? 'FR' : 'EN';
    }
    return 'FR';
  });

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  FR: {
    header: {
      about: 'À propos',
      howItWorks: 'Comment ça marche',
      features: 'Fonctionnalités',
      services: 'Services',
      faq: 'FAQ',
      downloadApp: 'Télécharger l\'App',
      recruitment: 'Recrutement',
    },
    hero: {
      availableInQuebec: 'Disponible au Québec',
      title: 'Soins Infirmiers',
      titleHighlight: 'Directement à Domicile',
      subtitle: 'Connectez-vous avec des infirmières qualifiées en quelques minutes. Service professionnel, sécurisé et disponible 24/7.',
      bookNow: 'Réserver Maintenant',
      pitchDeck: 'Pitch Deck',
      waitlistTitle: 'Liste d\'Attente',
      waitlistSubtitle: 'Soyez le premier averti et obtenez',
      waitlistDiscount: '20% de rabais',
      waitlistDiscountSuffix: 'au lancement.',
      emailPlaceholder: 'votre@email.com',
      successMessage: 'Inscrit !',
      errorMessage: 'Erreur',
      invalidEmail: 'Email invalide',
      personsRegistered: 'Personnes inscrites',
      patientsServed: 'Patients Traités',
      nextAppointment: 'Prochain Soin',
      highlights: 'Highlights',
      satisfaction: 'Satisfaction',
      network: 'Réseau',
      nurses: 'Inf.',
      zone: 'Zone',
      quebec: 'Québec',
      continueButton: 'Continuer',
      or: 'OU',
      continueWithApple: 'Continuer avec Apple',
      continueWithGoogle: 'Continuer avec Google',
      continueWithEmail: 'Continuer avec une adresse e-mail',
      findAccount: 'Retrouver votre compte',
      phoneNumber: 'Numéro de téléphone',
      getStarted: 'C\'est parti avec MobiSoins',
    },
    howItWorks: {
      title: 'Comment ça marche?',
      subtitle: 'MobiSoins simplifie l\'accès aux soins de santé à domicile.',
      step1Title: 'Réservez en 2 Minutes',
      step1Description: 'Choisissez votre service, l\'heure qui vous convient, et confirmez votre adresse. Notre IA trouve immédiatement les infirmières disponibles près de vous.',
      step2Title: 'Matching & Suivi en Temps Réel',
      step2Description: 'Notre algorithme sélectionne l\'infirmière la plus adaptée. Suivez son déplacement vers vous sur la carte en temps réel.',
      step3Title: 'Soins Professionnels à Domicile',
      step3Description: 'Profitez de soins de qualité hospitalière dans le confort de votre maison. Rapport clinique disponible dans l\'application après chaque visite.',
      step1: {
        title: 'Réservez en 2 Minutes',
        description: 'Choisissez votre service, l\'heure qui vous convient, et confirmez votre adresse. Notre IA trouve immédiatement les infirmières disponibles près de vous.',
      },
      step2: {
        title: 'Matching & Suivi en Temps Réel',
        description: 'Notre algorithme sélectionne l\'infirmière la plus adaptée. Suivez son déplacement vers vous sur la carte en temps réel.',
      },
      step3: {
        title: 'Soins Professionnels à Domicile',
        description: 'Profitez de soins de qualité hospitalière dans le confort de votre maison. Rapport clinique disponible dans l\'application après chaque visite.',
      },
    },
    features: {
      title: 'Des fonctionnalités conçues pour vous',
      subtitle: 'Profitez d\'une technologie de pointe conçue pour vous offrir la meilleure expérience de soins à domicile.',
      mainTitle: 'Une solution complète qui',
      mainTitleHighlight: 'simplifie vos soins.',
      mainSubtitle: 'Profitez d\'une technologie de pointe conçue pour vous offrir la meilleure expérience de soins à domicile.',
      geolocation: 'Géolocalisation',
      geolocationDescription: 'Suivez l\'arrivée de votre infirmière en temps réel sur la carte, comme pour un taxi.',
      secure: '100% Sécurisé',
      secureDescription: 'Vos données de santé sont chiffrées et protégées selon les normes les plus strictes.',
      certified: 'Certifié OIIQ',
      certifiedDescription: 'Toutes nos infirmières sont vérifiées et membres en règle de l\'ordre professionnel.',
      available: 'Disponible 24/7',
      availableDescription: 'Des soins accessibles jour et nuit, fin de semaine incluse, pour votre tranquillité d\'esprit.',
      aiMatching: {
        title: 'Matching IA Intelligent',
        description: 'Notre algorithme d\'IA connecte instantanément les patients avec l\'infirmière qualifiée la plus adaptée à leurs besoins, disponible dans leur secteur.',
      },
      tracking: {
        title: 'Suivi en Temps Réel',
        description: 'Visualisez l\'arrivée de votre infirmière sur la carte en temps réel. Notifications instantanées à chaque étape.',
      },
      scheduling: {
        title: 'Planification Automatique',
        description: 'Réservez en 2 minutes. Notre système gère les disponibilités, les rappels et les confirmations automatiquement.',
      },
      monitoring: {
        title: 'Suivi Clinique 24/7',
        description: 'Accès continu à votre historique de soins, vos rapports cliniques et l\'évolution de votre état de santé. Partagez facilement avec votre médecin.',
      },
      gpsLabel: 'Suivi GPS en temps réel',
      gpsTitle: 'Suivi en Temps Réel — localisez votre infirmière à chaque instant.',
      quebecLabel: 'Québec, Canada',
      activeNurses: '12 infirmières actives en ce moment',
      messagingLabel: 'Messagerie patient–infirmière',
      messagingTitle: 'Communication directe, instantanée, sécurisée.',
      chat: {
        patient: 'Bonjour, j\'ai besoin d\'une infirmière pour un pansement ce soir.',
        system: 'Correspondance trouvée — Sarah B., inf. OIIQ · 8 min de chez vous.',
        nurse: 'Bonjour ! Je suis en route, j\'arrive vers 18h45.',
        patientTime: 'Il y a 2 min',
        nurseTime: 'Maintenant',
      },
      stat: {
        matchTime: '< 2 min',
        matchLabel: 'Correspondance IA',
        satisfactionLabel: 'Taux de satisfaction',
        availabilityLabel: 'Disponibilité',
      },
      activity: {
        label: 'Activité de la plateforme',
        title: 'Croissance continue.',
        subtitle: 'Suivi en temps réel de chaque soin.',
      },
    },
    map: {
      badge: 'Dispatch en temps réel',
      title: 'Des soins à domicile en quelques minutes',
      description: 'Notre algorithme de dispatch connecte automatiquement chaque patient à l\'infirmière disponible la plus proche, certifiée OIIQ.',
      bullet1: 'Matching en moins de 60 secondes',
      bullet2: 'Infirmières certifiées OIIQ vérifiées',
      bullet3: 'Suivi GPS en temps réel',
    },
    services: {
      badge: 'Nos Avantages',
      mainTitle: 'Votre santé mérite',
      mainTitlePrefix: 'des',
      mainTitleHighlight: 'services',
      mainTitleSuffix: 'complets',
      card1Visual: 'Tableau de Bord',
      card1Item1: 'Prochain RDV',
      card1Item1Detail: 'Demain, 14:00',
      card1Item2: 'Médicaments',
      card1Item2Detail: 'Pris à 08:00',
      card1Badge: 'Suivi Personnalisé',
      card1Title: 'Tout au même endroit',
      card1Description: 'Gérez vos rendez-vous, suivez vos prescriptions et consultez votre historique de soins en un clin d\'œil.',
      card2Visual: 'Recherche Intelligente',
      card2Badge: 'Matching Précis',
      card2Title: 'Trouvez l\'Expert Idéal',
      card2Description: 'Notre algorithme vous connecte instantanément avec l\'infirmière qualifiée la plus proche de chez vous.',
      card3Visual: 'Vos Données',
      card3Badge: 'Suivi Clinique',
      card3Title: 'Visualisez vos progrès',
      card3Description: 'Des graphiques clairs et détaillés pour suivre l\'évolution de votre santé et partager vos rapports facilement.',
      mapBadge: 'Disponible à travers le Québec',
      bannerTitle: 'Soins à domicile partout',
      bannerTitleHighlight: 'au Québec.',
      bannerDescription: 'Infirmières certifiées OIIQ disponibles à Montréal, Québec, Laval, Longueuil, Sherbrooke, Gatineau et partout en province.',
      bannerCta: 'Rejoindre la liste d\'attente',
    },
    trust: {
      badge: 'Témoignages',
      title: 'Ce que nos patients disent',
      subtitle: 'Des milliers de patients et d\'infirmières font confiance à MobiSoins pour leurs soins à domicile.',
      testimonial1Headline: 'Un service exceptionnel',
      testimonial1Text: 'L\'application est intuitive et l\'infirmière est arrivée exactement à l\'heure prévue. Une expérience sans stress pour ma mère âgée.',
      testimonial2Headline: 'Rapidité incroyable',
      testimonial2Text: 'J\'ai pu réserver une prise de sang pour le lendemain matin. Résultats reçus directement dans l\'app. C\'est le futur!',
      testimonial3Headline: 'Professionnalisme au top',
      testimonial3Text: 'Infirmière très douce et compétente. Elle a pris le temps de tout expliquer. Je recommande MobiSoins à 100%.',
      testimonial4Headline: 'Sauveur de temps',
      testimonial4Text: 'Fini les attentes interminables en clinique. Le service à domicile change complètement la donne pour notre famille.',
      testimonial5Headline: 'Simplicité d\'utilisation',
      testimonial5Text: 'L\'interface est claire, le suivi en temps réel est rassurant. On sait exactement quand l\'infirmière arrive.',
      testimonial6Headline: 'Qualité hospitalière',
      testimonial6Text: 'Les soins reçus à la maison étaient de même qualité qu\'à l\'hôpital, mais dans le confort de mon salon.',
    },
    blog: {
      badge: 'Notre Blog',
      title: 'Derniers Articles',
      subtitle: 'Restez informé sur les dernières actualités en santé, les conseils de nos experts et les innovations MobiSoins.',
      readMore: 'Lire l\'article',
      readTime: 'lecture',
      article1Tag1: 'Innovation santé',
      article1Tag2: 'Télésanté',
      article1Title: 'Comment la télésanté transforme le suivi médical',
      article1Description: 'Et si consulter un professionnel de santé devenait aussi simple qu\'un appel vidéo ? La télésanté transforme le suivi médical en profondeur.',
      article2Tag1: 'Guide pratique',
      article2Tag2: 'Domicile',
      article2Title: 'Comment bien se préparer à sa première visite avec MobiSoins',
      article2Description: 'Recevoir des soins infirmiers à domicile, c\'est bénéficier d\'un suivi professionnel directement dans son environnement.',
      article3Tag1: 'Tendance santé',
      article3Tag2: 'Aînés',
      article3Title: 'Les avantages des soins à domicile pour les aînés',
      article3Description: 'Et si la meilleure place pour vieillir n\'était pas l\'hôpital… mais tout simplement chez soi ?',
    },
    faq: {
      title: 'Questions Fréquentes',
      subtitle: 'Trouvez des réponses à vos questions les plus courantes',
      searchPlaceholder: 'Rechercher une question...',
      noResults: 'Aucune question trouvée pour votre recherche.',
      question1: 'Comment fonctionne MobiSoins?',
      answer1: 'MobiSoins connecte les patients avec des infirmières certifiées pour des soins à domicile. Vous réservez via l\'application, suivez votre infirmière en temps réel, et payez de manière sécurisée après le service.',
      question2: 'Les infirmières sont-elles vraiment certifiées?',
      answer2: 'Oui, absolument. Toutes nos infirmières sont membres de l\'Ordre des Infirmières et Infirmiers du Québec (OIIQ), possèdent une assurance responsabilité civile, et ont passé notre processus de vérification rigoureux incluant la vérification des antécédents.',
      question3: 'Quels sont les coûts?',
      answer3: 'Les prix varient selon le service (45$ à 95$ en moyenne). Le prix exact est affiché avant la réservation. Aucun frais caché. Paiement sécurisé par carte de crédit ou Apple Pay.',
      question4: 'Quelles régions sont couvertes?',
      answer4: 'Actuellement disponible à Montréal, Québec, Laval, Gatineau, Longueuil, et Sherbrooke. Expansion prévue dans 10+ villes d\'ici fin 2027.',
      question5: 'Comment devenir infirmière partenaire?',
      answer5: 'Inscrivez-vous via notre formulaire \'Devenir Infirmière\'. Nous vérifions votre licence OIIQ, assurance, et effectuons une entrevue. Vous pouvez commencer à accepter des missions sous 5 jours ouvrables.',
      question6: 'Les paiements sont-ils sécurisés?',
      answer6: 'Oui, tous les paiements sont traités par Stripe, leader mondial en sécurité des paiements. Nous ne stockons jamais vos informations bancaires.',
      question7: 'Puis-je choisir mon infirmière?',
      answer7: 'Vous pouvez voir le profil, les évaluations, et l\'expérience de l\'infirmière avant d\'accepter la mission. Si vous avez une préférence, vous pouvez la demander pour vos prochaines visites.',
      question8: 'Que se passe-t-il en cas d\'urgence médicale?',
      answer8: 'MobiSoins n\'est PAS un service d\'urgence. En cas d\'urgence vitale, composez le 911. Nos infirmières peuvent gérer les soins non-urgents et vous orienter vers les urgences si nécessaire.',
    },
    contact: {
      title: 'Contactez-nous',
      description: 'Disponibles pour répondre à vos questions, collaborations ou partenariats. Nous vous répondons sous 24h.',
      detailsTitle: 'Coordonnées',
      phone: 'Téléphone',
      email: 'Courriel',
      web: 'Web',
      firstName: 'Prénom',
      firstNamePlaceholder: 'Prénom',
      lastName: 'Nom',
      lastNamePlaceholder: 'Nom',
      emailLabel: 'Courriel',
      emailPlaceholder: 'votre@courriel.com',
      subject: 'Sujet',
      subjectPlaceholder: 'Comment pouvons-nous vous aider ?',
      message: 'Message',
      messagePlaceholder: 'Décrivez votre demande en détail...',
      send: 'Envoyer le message',
      sending: 'Envoi en cours...',
      sent: '✓ Message envoyé !',
      sentConfirm: 'Merci ! Nous vous répondrons dans les 24h.',
    },
    stats: {
      patients: 'Patients servis',
      nurses: 'Infirmières OIIQ',
      satisfaction: 'Satisfaction',
      availability: 'Disponibilité',
      cities: 'Villes au Québec',
    },
    pillars: {
      badge: 'POURQUOI MOBISOINS',
      title: 'Conçu pour les soins modernes.',
      subtitle: 'Tout ce dont vous avez besoin pour recevoir ou dispenser des soins professionnels à domicile.',
      card1Title: 'Sécurité & Conformité',
      card1Desc: 'Toutes les infirmières sont membres actifs de l\'OIIQ. Vérification rigoureuse, assurance RC incluse, données de santé chiffrées.',
      card2Title: 'IA & Matching Intelligent',
      card2Desc: 'Notre algorithme analyse votre besoin et sélectionne instantanément l\'infirmière la plus qualifiée disponible près de chez vous.',
      card3Title: 'Expérience Patient',
      card3Desc: 'Interface intuitive, suivi en temps réel, rapports cliniques numériques. Des soins hospitaliers dans le confort de votre domicile.',
    },
    newsletter: {
      title: 'Rejoignez la liste d\'attente',
      subtitle: 'Commencez dès aujourd\'hui.',
      cta: 'S\'inscrire maintenant',
      description: 'Soyez parmi les premiers à profiter de l\'expérience MobiSoins et bénéficiez d\'avantages exclusifs au lancement.',
      emailPlaceholder: 'votre@email.com',
      submitButton: 'M\'inscrire',
      submitting: 'Envoi...',
      successTitle: 'Merci !',
      successMessage: 'Vous êtes inscrit à la liste d\'attente.',
      errorTitle: 'Erreur',
      errorMessage: 'Une erreur s\'est produite. Veuillez réessayer.',
      invalidEmailTitle: 'Email invalide',
      priorityAccess: 'Accès prioritaire',
      noCardRequired: 'Pas de carte requise',
    },
    about: {
      badge: 'À propos',
      title: 'À propos',
      description1: 'MobiSoins est une clinique mobile offrant des soins infirmiers professionnels à domicile et en ligne.',
      description2: 'Fondée par deux infirmières cliniciennes, MobiSoins a pour mission de rendre les soins de santé plus accessibles, rapides et sécuritaires, tout en plaçant la personne au cœur de chaque intervention.',
      description3: 'Grâce à une approche moderne alliant expertise clinique et innovation, nous offrons des services adaptés aux besoins de la population, dans le respect des plus hauts standards de pratique.',
      servicesTitle: 'Services',
      servicesIntro: 'MobiSoins offre une gamme complète de soins infirmiers adaptés à vos besoins, à domicile ou en ligne.',
      service1Title: 'Soins infirmiers',
      service1Desc: 'Pansements, retrait de points, administration de médicaments, soins post-opératoires et suivi clinique.',
      service2Title: 'Suivi des maladies chroniques',
      service2Desc: 'Suivi du diabète, de l\'hypertension et autres conditions, avec enseignement et prévention des complications.',
      service3Title: 'Bilan de santé',
      service3Desc: 'Évaluation complète, prise des signes vitaux et conseils personnalisés pour votre santé.',
      service4Title: 'Santé sexuelle',
      service4Desc: 'Dépistage ITSS, contraception, éducation et suivi.',
      service5Title: 'Soins aux aînés',
      service5Desc: 'Surveillance de la santé, gestion de la médication et soutien à domicile.',
      service6Title: 'Analyses et prélèvements',
      service6Desc: 'Prélèvements sanguins et tests diagnostiques, selon ordonnance.',
      service7Title: 'Services aux entreprises',
      service7Desc: 'Cliniques mobiles, bilans de santé et programmes de prévention en milieu de travail.',
    },
    footer: {
      description: 'MobiSoins révolutionne l\'accès aux soins de santé à domicile au Québec.',
      company: 'Entreprise',
      aboutUs: 'À propos',
      careers: 'Carrières',
      press: 'Presse',
      blog: 'Blog',
      services: 'Services',
      forPatients: 'Pour les patients',
      forNurses: 'Pour les infirmières',
      pricing: 'Tarification',
      insurance: 'Assurances',
      support: 'Support',
      helpCenter: 'Centre d\'aide',
      contact: 'Contact',
      privacy: 'Confidentialité',
      terms: 'Conditions',
      legal: 'Légal',
      privacyPolicy: 'Politique de confidentialité',
      termsOfService: 'Conditions d\'utilisation',
      cookies: 'Politique de cookies',
      allRightsReserved: 'Tous droits réservés.',
    },
  },
  EN: {
    header: {
      about: 'About',
      howItWorks: 'How It Works',
      features: 'Features',
      services: 'Services',
      faq: 'FAQ',
      downloadApp: 'Download App',
      recruitment: 'Recruitment',
    },
    hero: {
      availableInQuebec: 'Available in Quebec',
      title: 'Nursing Care',
      titleHighlight: 'Directly at Home',
      subtitle: 'Connect with qualified nurses in minutes. Professional, secure service available 24/7.',
      bookNow: 'Book Now',
      pitchDeck: 'Pitch Deck',
      waitlistTitle: 'Waiting List',
      waitlistSubtitle: 'Be the first to know and get',
      waitlistDiscount: '20% off',
      waitlistDiscountSuffix: 'at launch.',
      emailPlaceholder: 'your@email.com',
      successMessage: 'Registered!',
      errorMessage: 'Error',
      invalidEmail: 'Invalid email',
      personsRegistered: 'People registered',
      patientsServed: 'Patients Served',
      nextAppointment: 'Next Appointment',
      highlights: 'Highlights',
      satisfaction: 'Satisfaction',
      network: 'Network',
      nurses: 'Nurses',
      zone: 'Zone',
      quebec: 'Quebec',
      continueButton: 'Continue',
      or: 'OR',
      continueWithApple: 'Continue with Apple',
      continueWithGoogle: 'Continue with Google',
      continueWithEmail: 'Continue with email address',
      findAccount: 'Find your account',
      phoneNumber: 'Phone number',
      getStarted: 'Get started with MobiSoins',
    },
    howItWorks: {
      title: 'How does it work?',
      subtitle: 'MobiSoins simplifies access to home healthcare.',
      step1Title: 'Book in 2 Minutes',
      step1Description: 'Choose your service, the time that suits you, and confirm your address. Our AI immediately finds available nurses near you.',
      step2Title: 'Matching & Real-Time Tracking',
      step2Description: 'Our algorithm selects the most suitable nurse. Track her travel to you on the map in real-time.',
      step3Title: 'Professional Home Care',
      step3Description: 'Enjoy hospital-quality care in the comfort of your home. Clinical report available in the app after each visit.',
      step1: {
        title: 'Book in 2 Minutes',
        description: 'Choose your service, the time that suits you, and confirm your address. Our AI immediately finds available nurses near you.',
      },
      step2: {
        title: 'Matching & Real-Time Tracking',
        description: 'Our algorithm selects the most suitable nurse. Track her travel to you on the map in real-time.',
      },
      step3: {
        title: 'Professional Home Care',
        description: 'Enjoy hospital-quality care in the comfort of your home. Clinical report available in the app after each visit.',
      },
    },
    features: {
      title: 'Features designed for you',
      subtitle: 'Benefit from cutting-edge technology designed to offer you the best home care experience.',
      mainTitle: 'A complete solution that',
      mainTitleHighlight: 'simplifies your care.',
      mainSubtitle: 'Benefit from cutting-edge technology designed to offer you the best home care experience.',
      geolocation: 'Geolocation',
      geolocationDescription: 'Track your nurse\'s arrival in real-time on the map, just like a taxi.',
      secure: '100% Secure',
      secureDescription: 'Your health data is encrypted and protected according to the strictest standards.',
      certified: 'OIIQ Certified',
      certifiedDescription: 'All our nurses are verified and members in good standing of the professional order.',
      available: 'Available 24/7',
      availableDescription: 'Care accessible day and night, weekends included, for your peace of mind.',
      aiMatching: {
        title: 'Intelligent AI Matching',
        description: 'Our AI algorithm instantly connects patients with the most qualified nurse available in their area, tailored to their specific care needs.',
      },
      tracking: {
        title: 'Real-Time Tracking',
        description: 'Watch your nurse travel to you on the map in real-time. Instant notifications at every step of your care journey.',
      },
      scheduling: {
        title: 'Automated Scheduling',
        description: 'Book in 2 minutes. Our system manages availability, reminders, and confirmations automatically.',
      },
      monitoring: {
        title: '24/7 Clinical Monitoring',
        description: 'Continuous access to your care history, clinical reports, and health evolution tracking. Easily share with your physician.',
      },
      gpsLabel: 'Real-Time GPS Tracking',
      gpsTitle: 'Real-Time Tracking — locate your nurse at every moment.',
      quebecLabel: 'Quebec, Canada',
      activeNurses: '12 nurses active right now',
      messagingLabel: 'Patient–nurse messaging',
      messagingTitle: 'Direct, instant, secure communication.',
      chat: {
        patient: 'Hello, I need a nurse for a dressing change tonight.',
        system: 'Match found — Sarah B., OIIQ nurse · 8 min from you.',
        nurse: 'Hello! I\'m on my way, arriving around 6:45 PM.',
        patientTime: '2 min ago',
        nurseTime: 'Now',
      },
      stat: {
        matchTime: '< 2 min',
        matchLabel: 'AI Matching',
        satisfactionLabel: 'Satisfaction rate',
        availabilityLabel: 'Availability',
      },
      activity: {
        label: 'Platform activity',
        title: 'Continuous growth.',
        subtitle: 'Real-time tracking of every care session.',
      },
    },
    map: {
      badge: 'Real-time dispatch',
      title: 'Home care in just minutes',
      description: 'Our dispatch algorithm automatically connects each patient to the nearest available OIIQ-certified nurse.',
      bullet1: 'Matching in under 60 seconds',
      bullet2: 'Verified OIIQ-certified nurses',
      bullet3: 'Real-time GPS tracking',
    },
    services: {
      badge: 'Our Advantages',
      mainTitle: 'Your health deserves',
      mainTitlePrefix: 'complete',
      mainTitleHighlight: 'services',
      mainTitleSuffix: ' ',
      card1Visual: 'Dashboard',
      card1Item1: 'Next Appt',
      card1Item1Detail: 'Tomorrow, 2:00 PM',
      card1Item2: 'Medications',
      card1Item2Detail: 'Taken at 8:00 AM',
      card1Badge: 'Personalized Tracking',
      card1Title: 'Everything in one place',
      card1Description: 'Manage your appointments, track your prescriptions, and view your care history at a glance.',
      card2Visual: 'Smart Search',
      card2Badge: 'Precise Matching',
      card2Title: 'Find the Ideal Expert',
      card2Description: 'Our algorithm instantly connects you with the qualified nurse closest to you.',
      card3Visual: 'Your Data',
      card3Badge: 'Clinical Tracking',
      card3Title: 'Visualize your progress',
      card3Description: 'Clear and detailed charts to track your health evolution and easily share your reports.',
      mapBadge: 'Available across Quebec',
      bannerTitle: 'Home care everywhere',
      bannerTitleHighlight: 'in Quebec.',
      bannerDescription: 'OIIQ-certified nurses available in Montreal, Quebec City, Laval, Longueuil, Sherbrooke, Gatineau and throughout the province.',
      bannerCta: 'Join the waiting list',
    },
    trust: {
      badge: 'Testimonials',
      title: 'What our patients say',
      subtitle: 'Thousands of patients and nurses trust MobiSoins for their home healthcare needs.',
      testimonial1Headline: 'Exceptional service',
      testimonial1Text: 'The app is intuitive and the nurse arrived exactly on time. A stress-free experience for my elderly mother.',
      testimonial2Headline: 'Incredible speed',
      testimonial2Text: 'I was able to book a blood draw for the next morning. Results received directly in the app. This is the future!',
      testimonial3Headline: 'Top professionalism',
      testimonial3Text: 'Very gentle and competent nurse. She took the time to explain everything. I recommend MobiSoins 100%.',
      testimonial4Headline: 'Time saver',
      testimonial4Text: 'No more endless waits at the clinic. Home service completely changes the game for our family.',
      testimonial5Headline: 'Easy to use',
      testimonial5Text: 'The interface is clear, real-time tracking is reassuring. You know exactly when the nurse arrives.',
      testimonial6Headline: 'Hospital quality',
      testimonial6Text: 'The care received at home was the same quality as at the hospital, but in the comfort of my living room.',
    },
    blog: {
      badge: 'Our Blog',
      title: 'Latest Articles',
      subtitle: 'Stay informed about the latest health news, expert advice, and MobiSoins innovations.',
      readMore: 'Read article',
      readTime: 'read',
      article1Tag1: 'Health Innovation',
      article1Tag2: 'Telehealth',
      article1Title: 'How Telehealth Is Transforming Medical Monitoring',
      article1Description: 'What if consulting a healthcare professional were as simple as a video call? Telehealth is fundamentally transforming medical monitoring.',
      article2Tag1: 'Practical Guide',
      article2Tag2: 'Home',
      article2Title: 'How to Prepare for Your First Visit with MobiSoins',
      article2Description: 'Receiving home nursing care means benefiting from professional follow-up directly in your own environment.',
      article3Tag1: 'Health Trend',
      article3Tag2: 'Seniors',
      article3Title: 'The Benefits of Home Care for Seniors',
      article3Description: 'What if the best place to age wasn\'t the hospital... but simply at home?',
    },
    faq: {
      title: 'Frequently Asked Questions',
      subtitle: 'Find answers to your most common questions',
      searchPlaceholder: 'Search for a question...',
      noResults: 'No questions found for your search.',
      question1: 'How does MobiSoins work?',
      answer1: 'MobiSoins connects patients with certified nurses for home care. You book via the app, track your nurse in real-time, and pay securely after the service.',
      question2: 'Are the nurses really certified?',
      answer2: 'Yes, absolutely. All our nurses are members of the Quebec Order of Nurses (OIIQ), have liability insurance, and have passed our rigorous verification process including background checks.',
      question3: 'What are the costs?',
      answer3: 'Prices vary by service ($45 to $95 on average). The exact price is displayed before booking. No hidden fees. Secure payment by credit card or Apple Pay.',
      question4: 'Which regions are covered?',
      answer4: 'Currently available in Montreal, Quebec City, Laval, Gatineau, Longueuil, and Sherbrooke. Expansion planned in 10+ cities by the end of 2027.',
      question5: 'How to become a partner nurse?',
      answer5: 'Sign up via our \'Become a Nurse\' form. We verify your OIIQ license, insurance, and conduct an interview. You can start accepting missions within 5 business days.',
      question6: 'Are payments secure?',
      answer6: 'Yes, all payments are processed by Stripe, a global leader in payment security. We never store your banking information.',
      question7: 'Can I choose my nurse?',
      answer7: 'You can see the profile, ratings, and experience of the nurse before accepting the mission. If you have a preference, you can request them for your next visits.',
      question8: 'What happens in case of a medical emergency?',
      answer8: 'MobiSoins is NOT an emergency service. In case of a life-threatening emergency, dial 911. Our nurses can handle non-urgent care and direct you to the emergency room if necessary.',
    },
    contact: {
      title: 'Contact Us',
      description: 'Available for questions, feedback, or partnership opportunities. We respond within 24 hours.',
      detailsTitle: 'Contact Details',
      phone: 'Phone',
      email: 'Email',
      web: 'Web',
      firstName: 'First Name',
      firstNamePlaceholder: 'First Name',
      lastName: 'Last Name',
      lastNamePlaceholder: 'Last Name',
      emailLabel: 'Email',
      emailPlaceholder: 'your@email.com',
      subject: 'Subject',
      subjectPlaceholder: 'How can we help you?',
      message: 'Message',
      messagePlaceholder: 'Describe your request in detail...',
      send: 'Send Message',
      sending: 'Sending...',
      sent: '✓ Message Sent!',
      sentConfirm: 'Thank you! We will respond within 24 hours.',
    },
    stats: {
      patients: 'Patients served',
      nurses: 'OIIQ Nurses',
      satisfaction: 'Satisfaction',
      availability: 'Availability',
      cities: 'Cities in Quebec',
    },
    pillars: {
      badge: 'WHY MOBISOINS',
      title: 'Built for modern care.',
      subtitle: 'Everything you need to receive or deliver professional home healthcare.',
      card1Title: 'Safety & Compliance',
      card1Desc: 'All nurses are active OIIQ members. Rigorous verification, liability insurance included, encrypted health data.',
      card2Title: 'AI & Smart Matching',
      card2Desc: 'Our algorithm analyzes your needs and instantly selects the most qualified available nurse near you.',
      card3Title: 'Patient Experience',
      card3Desc: 'Intuitive interface, real-time tracking, digital clinical reports. Hospital-quality care in the comfort of your home.',
    },
    newsletter: {
      title: 'Join the Waiting List',
      subtitle: 'Get started today.',
      cta: 'Sign up now',
      description: 'Be among the first to experience MobiSoins and enjoy exclusive benefits at launch.',
      emailPlaceholder: 'your@email.com',
      submitButton: 'Sign Up',
      submitting: 'Sending...',
      successTitle: 'Thank you!',
      successMessage: 'You are registered on the waiting list.',
      errorTitle: 'Error',
      errorMessage: 'An error occurred. Please try again.',
      invalidEmailTitle: 'Invalid email',
      priorityAccess: 'Priority access',
      noCardRequired: 'No card required',
    },
    about: {
      badge: 'About',
      title: 'About Us',
      description1: 'MobiSoins is a mobile clinic offering professional nursing care at home and online.',
      description2: 'Founded by two clinical nurses, MobiSoins\' mission is to make healthcare more accessible, faster and safer, while placing the person at the heart of every intervention.',
      description3: 'Through a modern approach combining clinical expertise and innovation, we offer services tailored to the needs of the population, in accordance with the highest standards of practice.',
      servicesTitle: 'Services',
      servicesIntro: 'MobiSoins offers a complete range of nursing care tailored to your needs, at home or online.',
      service1Title: 'Nursing Care',
      service1Desc: 'Wound dressing, suture removal, medication administration, post-operative care and clinical follow-up.',
      service2Title: 'Chronic Disease Management',
      service2Desc: 'Diabetes, hypertension and other condition monitoring, with education and complication prevention.',
      service3Title: 'Health Assessment',
      service3Desc: 'Complete evaluation, vital signs monitoring and personalized health advice.',
      service4Title: 'Sexual Health',
      service4Desc: 'STI screening, contraception, education and follow-up.',
      service5Title: 'Senior Care',
      service5Desc: 'Health monitoring, medication management and home support.',
      service6Title: 'Lab Tests & Samples',
      service6Desc: 'Blood draws and diagnostic tests, by prescription.',
      service7Title: 'Corporate Services',
      service7Desc: 'Mobile clinics, health assessments and workplace prevention programs.',
    },
    footer: {
      description: 'MobiSoins is revolutionizing access to home healthcare in Quebec.',
      company: 'Company',
      aboutUs: 'About Us',
      careers: 'Careers',
      press: 'Press',
      blog: 'Blog',
      services: 'Services',
      forPatients: 'For Patients',
      forNurses: 'For Nurses',
      pricing: 'Pricing',
      insurance: 'Insurance',
      support: 'Support',
      helpCenter: 'Help Center',
      contact: 'Contact',
      privacy: 'Privacy',
      terms: 'Terms',
      legal: 'Legal',
      privacyPolicy: 'Privacy Policy',
      termsOfService: 'Terms of Service',
      cookies: 'Cookie Policy',
      allRightsReserved: 'All rights reserved.',
    },
  },
};



