import React, { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

type Language = 'FR' | 'EN';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('FR');

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  FR: {
    header: {
      howItWorks: 'Comment ça marche',
      features: 'Fonctionnalités',
      services: 'Services',
      faq: 'FAQ',
      downloadApp: 'Télécharger l\'App',
      recruitment: 'Recrutement',
    },
    hero: {
      availableInQuebec: 'Disponible au Québec',
      title: 'Soins Infirmiers',
      titleHighlight: 'Directement à Domicile',
      subtitle: 'Connectez-vous avec des infirmières qualifiées en quelques minutes. Service professionnel, sécurisé et disponible 24/7.',
      bookNow: 'Réserver Maintenant',
      pitchDeck: 'Pitch Deck',
      waitlistTitle: 'Liste d\'Attente',
      waitlistSubtitle: 'Soyez le premier averti et obtenez',
      waitlistDiscount: '20% de rabais',
      waitlistDiscountSuffix: 'au lancement.',
      emailPlaceholder: 'votre@email.com',
      successMessage: 'Inscrit !',
      errorMessage: 'Erreur',
      invalidEmail: 'Email invalide',
      personsRegistered: 'Personnes inscrites',
      patientsServed: 'Patients Traités',
      nextAppointment: 'Prochain Soin',
      highlights: 'Highlights',
      satisfaction: 'Satisfaction',
      network: 'Réseau',
      nurses: 'Inf.',
      zone: 'Zone',
      quebec: 'Québec',
      continueButton: 'Continuer',
      or: 'OU',
      continueWithApple: 'Continuer avec Apple',
      continueWithGoogle: 'Continuer avec Google',
      continueWithEmail: 'Continuer avec une adresse e-mail',
      findAccount: 'Retrouver votre compte',
      phoneNumber: 'Numéro de téléphone',
      getStarted: 'C\'est parti avec MobiSoins',
    },
    howItWorks: {
      title: 'Comment ça marche?',
      subtitle: 'MobiSoins simplifie l\'accès aux soins de santé à domicile.',
      step1Title: 'Réservez en 2 Minutes',
      step1Description: 'Choisissez votre service, l\'heure qui vous convient, et confirmez votre adresse.',
      step2Title: 'Suivi en Temps Réel',
      step2Description: 'Voyez votre infirmière se déplacer vers vous sur la carte en temps réel.',
      step3Title: 'Soins Professionnels',
      step3Description: 'Profitez de soins de qualité hospitalière dans le confort de votre maison.',
    },
    features: {
      mainTitle: 'Une solution complète qui',
      mainTitleHighlight: 'simplifie vos soins.',
      mainSubtitle: 'Profitez d\'une technologie de pointe conçue pour vous offrir la meilleure expérience de soins à domicile.',
      geolocation: 'Géolocalisation',
      geolocationDescription: 'Suivez l\'arrivée de votre infirmière en temps réel sur la carte, comme pour un taxi.',
      secure: '100% Sécurisé',
      secureDescription: 'Vos données de santé sont chiffrées et protégées selon les normes les plus strictes.',
      certified: 'Certifié OIIQ',
      certifiedDescription: 'Toutes nos infirmières sont vérifiées et membres en règle de l\'ordre professionnel.',
      available: 'Disponible 24/7',
      availableDescription: 'Des soins accessibles jour et nuit, fin de semaine incluse, pour votre tranquillité d\'esprit.',
    },
    services: {
      badge: 'Nos Avantages',
      mainTitle: 'Votre santé mérite',
      mainTitlePrefix: 'ces',
      mainTitleHighlight: 'services',
      mainTitleSuffix: 'complets',
      card1Visual: 'Tableau de Bord',
      card1Item1: 'Prochain RDV',
      card1Item1Detail: 'Demain, 14:00',
      card1Item2: 'Médicaments',
      card1Item2Detail: 'Pris à 08:00',
      card1Badge: 'Suivi Personnalisé',
      card1Title: 'Tout au même endroit',
      card1Description: 'Gérez vos rendez-vous, suivez vos prescriptions et consultez votre historique de soins en un clin d\'œil.',
      card2Visual: 'Recherche Intelligente',
      card2Badge: 'Matching Précis',
      card2Title: 'Trouvez l\'Expert Idéal',
      card2Description: 'Notre algorithme vous connecte instantanément avec l\'infirmière qualifiée la plus proche de chez vous.',
      card3Visual: 'Vos Données',
      card3Badge: 'Suivi Clinique',
      card3Title: 'Visualisez vos progrès',
      card3Description: 'Des graphiques clairs et détaillés pour suivre l\'évolution de votre santé et partager vos rapports facilement.',
    },
    trust: {
      badge: 'Témoignages',
      title: 'Ce que nos patients',
      subtitle: 'disent de nous',
      testimonial1Headline: 'Un service exceptionnel',
      testimonial1Text: 'L\'application est intuitive et l\'infirmière est arrivée exactement à l\'heure prévue. Une expérience sans stress pour ma mère âgée.',
      testimonial2Headline: 'Rapidité incroyable',
      testimonial2Text: 'J\'ai pu réserver une prise de sang pour le lendemain matin. Résultats reçus directement dans l\'app. C\'est le futur!',
      testimonial3Headline: 'Professionnalisme au top',
      testimonial3Text: 'Infirmière très douce et compétente. Elle a pris le temps de tout expliquer. Je recommande MobiSoins à 100%.',
      testimonial4Headline: 'Sauveur de temps',
      testimonial4Text: 'Fini les attentes interminables en clinique. Le service à domicile change complètement la donne pour notre famille.',
      testimonial5Headline: 'Simplicité d\'utilisation',
      testimonial5Text: 'L\'interface est claire, le suivi en temps réel est rassurant. On sait exactement quand l\'infirmière arrive.',
      testimonial6Headline: 'Qualité hospitalière',
      testimonial6Text: 'Les soins reçus à la maison étaient de même qualité qu\'à l\'hôpital, mais dans le confort de mon salon.',
    },
    blog: {
      badge: 'Notre Blog',
      title: 'Derniers Articles',
      subtitle: 'Restez informé sur les dernières actualités en santé, les conseils de nos experts et les innovations MobiSoins.',
      readMore: 'Lire l\'article',
      article1Tag1: 'Santé',
      article1Tag2: 'Domicile',
      article1Title: 'Les avantages des soins à domicile pour les aînés',
      article1Description: 'Découvrez comment les soins à domicile améliorent la qualité de vie et l\'autonomie des personnes âgées au Québec.',
      article2Tag1: 'Technologie',
      article2Tag2: 'Innovation',
      article2Title: 'Comment la télé-santé transforme le suivi médical',
      article2Description: 'L\'impact des nouvelles technologies sur la relation patient-soignant et l\'accessibilité aux soins.',
      article3Tag1: 'Bien-être',
      article3Tag2: 'Conseils',
      article3Title: 'Préparer sa première visite infirmière',
      article3Description: 'Guide complet pour vous préparer à recevoir des soins infirmiers professionnels dans le confort de votre foyer.',
    },
    faq: {
      title: 'Questions Fréquentes',
      subtitle: 'Trouvez des réponses à vos questions les plus courantes',
      searchPlaceholder: 'Rechercher une question...',
      noResults: 'Aucune question trouvée pour votre recherche.',
      question1: 'Comment fonctionne MobiSoins?',
      answer1: 'MobiSoins connecte les patients avec des infirmières certifiées pour des soins à domicile. Vous réservez via l\'application, suivez votre infirmière en temps réel, et payez de manière sécurisée après le service.',
      question2: 'Les infirmières sont-elles vraiment certifiées?',
      answer2: 'Oui, absolument. Toutes nos infirmières sont membres de l\'Ordre des Infirmières et Infirmiers du Québec (OIIQ), possèdent une assurance responsabilité civile, et ont passé notre processus de vérification rigoureux incluant la vérification des antécédents.',
      question3: 'Quels sont les coûts?',
      answer3: 'Les prix varient selon le service (45$ à 95$ en moyenne). Le prix exact est affiché avant la réservation. Aucun frais caché. Paiement sécurisé par carte de crédit ou Apple Pay.',
      question4: 'Quelles régions sont couvertes?',
      answer4: 'Actuellement disponible à Montréal, Québec, Laval, Gatineau, Longueuil, et Sherbrooke. Expansion prévue dans 10+ villes d\'ici fin 2025.',
      question5: 'Comment devenir infirmière partenaire?',
      answer5: 'Inscrivez-vous via notre formulaire \'Devenir Infirmière\'. Nous vérifions votre licence OIIQ, assurance, et effectuons une entrevue. Vous pouvez commencer à accepter des missions sous 5 jours ouvrables.',
      question6: 'Les paiements sont-ils sécurisés?',
      answer6: 'Oui, tous les paiements sont traités par Stripe, leader mondial en sécurité des paiements. Nous ne stockons jamais vos informations bancaires.',
      question7: 'Puis-je choisir mon infirmière?',
      answer7: 'Vous pouvez voir le profil, les évaluations, et l\'expérience de l\'infirmière avant d\'accepter la mission. Si vous avez une préférence, vous pouvez la demander pour vos prochaines visites.',
      question8: 'Que se passe-t-il en cas d\'urgence médicale?',
      answer8: 'MobiSoins n\'est PAS un service d\'urgence. En cas d\'urgence vitale, composez le 911. Nos infirmières peuvent gérer les soins non-urgents et vous orienter vers les urgences si nécessaire.',
    },
    newsletter: {
      title: 'Rejoignez la liste d\'attente',
      subtitle: 'Commencez dès aujourd\'hui',
      description: 'Soyez parmi les premiers à profiter de l\'expérience MobiSoins et bénéficiez d\'avantages exclusifs au lancement.',
      emailPlaceholder: 'votre@email.com',
      submitButton: 'M\'inscrire',
      submitting: 'Envoi...',
      successTitle: 'Merci !',
      successMessage: 'Vous êtes inscrit à la liste d\'attente.',
      errorTitle: 'Erreur',
      errorMessage: 'Une erreur s\'est produite. Veuillez réessayer.',
      invalidEmailTitle: 'Email invalide',
      priorityAccess: 'Accès prioritaire',
      noCardRequired: 'Pas de carte requise',
    },
    footer: {
      description: 'MobiSoins révolutionne l\'accès aux soins de santé à domicile au Québec.',
      company: 'Entreprise',
      aboutUs: 'À propos',
      careers: 'Carrières',
      press: 'Presse',
      blog: 'Blog',
      services: 'Services',
      forPatients: 'Pour les patients',
      forNurses: 'Pour les infirmières',
      pricing: 'Tarification',
      insurance: 'Assurances',
      support: 'Support',
      helpCenter: 'Centre d\'aide',
      contact: 'Contact',
      privacy: 'Confidentialité',
      terms: 'Conditions',
      legal: 'Légal',
      privacyPolicy: 'Politique de confidentialité',
      termsOfService: 'Conditions d\'utilisation',
      cookies: 'Politique de cookies',
      allRightsReserved: 'Tous droits réservés.',
    },
  },
  EN: {
    header: {
      howItWorks: 'How It Works',
      features: 'Features',
      services: 'Services',
      faq: 'FAQ',
      downloadApp: 'Download App',
      recruitment: 'Recruitment',
    },
    hero: {
      availableInQuebec: 'Available in Quebec',
      title: 'Nursing Care',
      titleHighlight: 'Directly at Home',
      subtitle: 'Connect with qualified nurses in minutes. Professional, secure service available 24/7.',
      bookNow: 'Book Now',
      pitchDeck: 'Pitch Deck',
      waitlistTitle: 'Waiting List',
      waitlistSubtitle: 'Be the first to know and get',
      waitlistDiscount: '20% off',
      waitlistDiscountSuffix: 'at launch.',
      emailPlaceholder: 'your@email.com',
      successMessage: 'Registered!',
      errorMessage: 'Error',
      invalidEmail: 'Invalid email',
      personsRegistered: 'People registered',
      patientsServed: 'Patients Served',
      nextAppointment: 'Next Appointment',
      highlights: 'Highlights',
      satisfaction: 'Satisfaction',
      network: 'Network',
      nurses: 'Nurses',
      zone: 'Zone',
      quebec: 'Quebec',
      continueButton: 'Continue',
      or: 'OR',
      continueWithApple: 'Continue with Apple',
      continueWithGoogle: 'Continue with Google',
      continueWithEmail: 'Continue with email address',
      findAccount: 'Find your account',
      phoneNumber: 'Phone number',
      getStarted: 'Get started with MobiSoins',
    },
    howItWorks: {
      title: 'How does it work?',
      subtitle: 'MobiSoins simplifies access to home healthcare.',
      step1Title: 'Book in 2 Minutes',
      step1Description: 'Choose your service, the time that suits you, and confirm your address.',
      step2Title: 'Real-Time Tracking',
      step2Description: 'Watch your nurse travel to you on the map in real-time.',
      step3Title: 'Professional Care',
      step3Description: 'Enjoy hospital-quality care in the comfort of your home.',
    },
    features: {
      mainTitle: 'A complete solution that',
      mainTitleHighlight: 'simplifies your care.',
      mainSubtitle: 'Benefit from cutting-edge technology designed to offer you the best home care experience.',
      geolocation: 'Geolocation',
      geolocationDescription: 'Track your nurse\'s arrival in real-time on the map, just like a taxi.',
      secure: '100% Secure',
      secureDescription: 'Your health data is encrypted and protected according to the strictest standards.',
      certified: 'OIIQ Certified',
      certifiedDescription: 'All our nurses are verified and members in good standing of the professional order.',
      available: 'Available 24/7',
      availableDescription: 'Care accessible day and night, weekends included, for your peace of mind.',
    },
    services: {
      badge: 'Our Advantages',
      mainTitle: 'Your health deserves',
      mainTitlePrefix: 'these',
      mainTitleHighlight: 'services',
      mainTitleSuffix: 'complete',
      card1Visual: 'Dashboard',
      card1Item1: 'Next Appt',
      card1Item1Detail: 'Tomorrow, 2:00 PM',
      card1Item2: 'Medications',
      card1Item2Detail: 'Taken at 8:00 AM',
      card1Badge: 'Personalized Tracking',
      card1Title: 'Everything in one place',
      card1Description: 'Manage your appointments, track your prescriptions, and view your care history at a glance.',
      card2Visual: 'Smart Search',
      card2Badge: 'Precise Matching',
      card2Title: 'Find the Ideal Expert',
      card2Description: 'Our algorithm instantly connects you with the qualified nurse closest to you.',
      card3Visual: 'Your Data',
      card3Badge: 'Clinical Tracking',
      card3Title: 'Visualize your progress',
      card3Description: 'Clear and detailed charts to track your health evolution and easily share your reports.',
    },
    trust: {
      badge: 'Testimonials',
      title: 'What our patients',
      subtitle: 'say about us',
      testimonial1Headline: 'Exceptional service',
      testimonial1Text: 'The app is intuitive and the nurse arrived exactly on time. A stress-free experience for my elderly mother.',
      testimonial2Headline: 'Incredible speed',
      testimonial2Text: 'I was able to book a blood draw for the next morning. Results received directly in the app. This is the future!',
      testimonial3Headline: 'Top professionalism',
      testimonial3Text: 'Very gentle and competent nurse. She took the time to explain everything. I recommend MobiSoins 100%.',
      testimonial4Headline: 'Time saver',
      testimonial4Text: 'No more endless waits at the clinic. Home service completely changes the game for our family.',
      testimonial5Headline: 'Easy to use',
      testimonial5Text: 'The interface is clear, real-time tracking is reassuring. You know exactly when the nurse arrives.',
      testimonial6Headline: 'Hospital quality',
      testimonial6Text: 'The care received at home was the same quality as at the hospital, but in the comfort of my living room.',
    },
    blog: {
      badge: 'Our Blog',
      title: 'Latest Articles',
      subtitle: 'Stay informed about the latest health news, expert advice, and MobiSoins innovations.',
      readMore: 'Read article',
      article1Tag1: 'Health',
      article1Tag2: 'Home',
      article1Title: 'The benefits of home care for seniors',
      article1Description: 'Discover how home care improves the quality of life and autonomy of elderly people in Quebec.',
      article2Tag1: 'Technology',
      article2Tag2: 'Innovation',
      article2Title: 'How telehealth is transforming medical monitoring',
      article2Description: 'The impact of new technologies on the patient-caregiver relationship and accessibility to care.',
      article3Tag1: 'Wellness',
      article3Tag2: 'Tips',
      article3Title: 'Preparing for your first nursing visit',
      article3Description: 'Complete guide to prepare you to receive professional nursing care in the comfort of your home.',
    },
    faq: {
      title: 'Frequently Asked Questions',
      subtitle: 'Find answers to your most common questions',
      searchPlaceholder: 'Search for a question...',
      noResults: 'No questions found for your search.',
      question1: 'How does MobiSoins work?',
      answer1: 'MobiSoins connects patients with certified nurses for home care. You book via the app, track your nurse in real-time, and pay securely after the service.',
      question2: 'Are the nurses really certified?',
      answer2: 'Yes, absolutely. All our nurses are members of the Quebec Order of Nurses (OIIQ), have liability insurance, and have passed our rigorous verification process including background checks.',
      question3: 'What are the costs?',
      answer3: 'Prices vary by service ($45 to $95 on average). The exact price is displayed before booking. No hidden fees. Secure payment by credit card or Apple Pay.',
      question4: 'Which regions are covered?',
      answer4: 'Currently available in Montreal, Quebec City, Laval, Gatineau, Longueuil, and Sherbrooke. Expansion planned in 10+ cities by the end of 2025.',
      question5: 'How to become a partner nurse?',
      answer5: 'Sign up via our \'Become a Nurse\' form. We verify your OIIQ license, insurance, and conduct an interview. You can start accepting missions within 5 business days.',
      question6: 'Are payments secure?',
      answer6: 'Yes, all payments are processed by Stripe, a global leader in payment security. We never store your banking information.',
      question7: 'Can I choose my nurse?',
      answer7: 'You can see the profile, ratings, and experience of the nurse before accepting the mission. If you have a preference, you can request them for your next visits.',
      question8: 'What happens in case of a medical emergency?',
      answer8: 'MobiSoins is NOT an emergency service. In case of a life-threatening emergency, dial 911. Our nurses can handle non-urgent care and direct you to the emergency room if necessary.',
    },
    newsletter: {
      title: 'Join the Waiting List',
      subtitle: 'Get Started Today',
      description: 'Be among the first to experience MobiSoins and enjoy exclusive benefits at launch.',
      emailPlaceholder: 'your@email.com',
      submitButton: 'Sign Up',
      submitting: 'Sending...',
      successTitle: 'Thank you!',
      successMessage: 'You are registered on the waiting list.',
      errorTitle: 'Error',
      errorMessage: 'An error occurred. Please try again.',
      invalidEmailTitle: 'Invalid email',
      priorityAccess: 'Priority access',
      noCardRequired: 'No card required',
    },
    footer: {
      description: 'MobiSoins is revolutionizing access to home healthcare in Quebec.',
      company: 'Company',
      aboutUs: 'About Us',
      careers: 'Careers',
      press: 'Press',
      blog: 'Blog',
      services: 'Services',
      forPatients: 'For Patients',
      forNurses: 'For Nurses',
      pricing: 'Pricing',
      insurance: 'Insurance',
      support: 'Support',
      helpCenter: 'Help Center',
      contact: 'Contact',
      privacy: 'Privacy',
      terms: 'Terms',
      legal: 'Legal',
      privacyPolicy: 'Privacy Policy',
      termsOfService: 'Terms of Service',
      cookies: 'Cookie Policy',
      allRightsReserved: 'All rights reserved.',
    },
  },
};



